[platformio]
default_envs = esp32s2
src_dir = examples/BasicPIO/src

[env:esp32s2]
platform = espressif32
board = esp32-s2-saola-1       ; or your exact S2 board id
framework = arduino
monitor_speed = 115200
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
lib_extra_dirs = .
