[platformio]
default_envs = esp32s2_usb
src_dir = examples/BasicPIO/src

[env]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 2000000
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MANUFACTURER="Thymos Solution"
    -DARDUINO_USB_PRODUCT="ESP32 USB Device"
    ; OPTIONAL: if you want a fixed VID/PID from esp-idf/Arduino USB stack
    -DUSB_VID=0x303A          ; example: Espressif VID (only if you have an assigned PID!)
    -DUSB_PID=0x8001          ; example custom PID - replace with your real one
lib_extra_dirs = .

[env:esp32s2_usb]
;upload_port = COM3
build_type = release       ; uses -Os by default
;monitor_port = COM8

[env:esp32s2_jtag]
debug_tool = esp-prog
upload_protocol = esp-prog
;upload_port = COM5
debug_init_break = tbreak setup
monitor_filters = colorize, esp32_exception_decoder, send_on_enter
monitor_eol = LF
monitor_rts = 0
monitor_echo = yes
build_type = debug         ; uses -Og -g3, etc.

[env:esp32s2_jtag2]
;upload_port = COM5
upload_protocol = esp-bridge
monitor_filters = colorize, esp32_exception_decoder, send_on_enter
monitor_eol = LF
; Custom debug tool so we can point to the right OpenOCD config
debug_tool = custom
debug_speed = 5000
debug_server =
  ${platformio.packages_dir}/tool-openocd-esp32/bin/openocd
  -s ${platformio.packages_dir}/tool-openocd-esp32/share/openocd/scripts
  -f board/esp32s2-bridge.cfg
debug_init_break = tbreak setup
monitor_rts = 0
monitor_echo = yes
build_type = debug         ; uses -Og -g3, etc.
