/**
 * @file Version.h
 * @brief Library version information.
 * 
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version in library.json instead.
 * 
 * Generated: 2026-02-10 08:09:35
 * Git commit: 9b4f7df (clean)
 */

#pragma once

#include <stdint.h>

namespace SystemChrono {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (new features, backward compatible).
static constexpr uint16_t VERSION_MINOR = 1;

/// @brief Patch version (bug fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full version string (e.g., "1.2.3").
static constexpr const char* VERSION = "1.1.0";

/// @brief Encoded version for numeric comparison.
/// @note Format: MAJOR*10000 + MINOR*100 + PATCH
/// @note Example: version 1.2.3 = 10203
static constexpr uint32_t VERSION_CODE = 10100;

/// @brief Build date (YYYY-MM-DD).
static constexpr const char* BUILD_DATE = "2026-02-10";

/// @brief Build time (HH:MM:SS).
static constexpr const char* BUILD_TIME = "08:09:35";

/// @brief Full build timestamp.
static constexpr const char* BUILD_TIMESTAMP = "2026-02-10 08:09:35";

/// @brief Git commit hash (short).
static constexpr const char* GIT_COMMIT = "9b4f7df";

/// @brief Git working tree status ("clean" or "dirty").
/// @note "dirty" means there are uncommitted changes.
static constexpr const char* GIT_STATUS = "clean";

/// @brief Full version string with build info.
/// @note Format: "version (commit, date time)"
static constexpr const char* VERSION_FULL = "1.1.0 (9b4f7df, 2026-02-10 08:09:35)";

}  // namespace SystemChrono
