/**
 * @file Version.h
 * @brief Library version information.
 * 
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version in library.json instead.
 * 
 * Generated: 2026-01-12 18:19:43
 * Git commit: e9b25e5 (dirty)
 */

#pragma once

#include <stdint.h>

namespace SystemChrono {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 2;

/// @brief Minor version (new features, backward compatible).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (bug fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full version string (e.g., "1.2.3").
static constexpr const char* VERSION = "2.0.0";

/// @brief Encoded version for numeric comparison.
/// @note Format: MAJOR*10000 + MINOR*100 + PATCH
/// @note Example: version 1.2.3 = 10203
static constexpr uint32_t VERSION_CODE = 20000;

/// @brief Build date (YYYY-MM-DD).
static constexpr const char* BUILD_DATE = "2026-01-12";

/// @brief Build time (HH:MM:SS).
static constexpr const char* BUILD_TIME = "18:19:43";

/// @brief Full build timestamp.
static constexpr const char* BUILD_TIMESTAMP = "2026-01-12 18:19:43";

/// @brief Git commit hash (short).
static constexpr const char* GIT_COMMIT = "e9b25e5";

/// @brief Git working tree status ("clean" or "dirty").
/// @note "dirty" means there are uncommitted changes.
static constexpr const char* GIT_STATUS = "dirty";

/// @brief Full version string with build info.
/// @note Format: "version (commit, date time)"
static constexpr const char* VERSION_FULL = "2.0.0 (e9b25e5, 2026-01-12 18:19:43)";

}  // namespace SystemChrono
